gemfile: .overcommit/Gemfile

# Hooks that are run after `git commit` is executed, before the commit message
# editor is displayed. These hooks are ideal for syntax checkers, linters, and
# other checks that you want to run before you allow a commit object to be
# created.
PreCommit:
  RuboCop:
    enabled: true
    required_executable: 'rubocop'
    flags: ['--format=emacs', '--force-exclusion', '--display-cop-names']
    install_command: 'gem install rubocop'
    include:
      - '**/*.gemspec'
      - '**/*.rake'
      - '**/*.rb'
      - '**/*.ru'
      - '**/Gemfile'
      - '**/Rakefile'
  YamlSyntax:
    enabled: true
  BundleCheck:
    enabled: true
  Fasterer:
    enabled: true
  BundleAudit:
    enabled: true
  Reek:
    enabled: true
# Hooks that run during `git push`, after remote refs have been updated but
# before any objects have been transferred.
PrePush:
  RSpec:
    enabled: true
    description: 'Run RSpec test suite'
    required_executable: '.bundle/bin/rake'
    command: [ 'rake', 'spec' ]
