AllCops:
  Exclude:
    - 'vendor/**/*'
Layout/MultilineMethodCallIndentation: { EnforcedStyle: indented }
Metrics/BlockLength: { Exclude: ['spec/**/*.rb'] }
Naming/UncommunicativeMethodParamName: { AllowedNames: [] }
Style/AccessModifierDeclarations: { EnforcedStyle: inline }
Style/Documentation: { Enabled: False }
