# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

group :development do
  gem 'args', github: 'mouchtaris/gems', branch: 'args/master'
  gem 'buffer', github: 'mouchtaris/gems', branch: 'buffer/master'
  gem 'mry'
  gem 'pry-byebug'
  gem 'rspec'
  gem 'rubocop'
end

# Specify your gem's dependencies in ruby.gemspec
gemspec
